version: '2'
services:
  django:
    build: ./django_container
    restart: unless-stopped
    expose:
      - "8000"
    ports:
      - "8000:8000"
    # Development mode
    command: python manage.py runserver 0:8000
    environment:
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/src/.local/bin
      - PYTHONPATH=/src/.local/lib/python2.7/site-packages/
    env_file:
      - django_container/setup/env
    volumes:
      # Editable
      - ./django_container/src/pysmve/:/src/pysmve/
      # Preserve static files on restarts
      - ./django_container/static/:/src/static/
    depends_on:
      - postgres

  postgres:
      image: postgres:9.5
      restart: unless-stopped
      expose:
        - "5432"
      ports:
        - "5432:5432"
      env_file:
        - django_container/setup/env
