FORWARDER_SUBSCRIBER_TRANSPORT = FORWARDER_PUBLISHER_TRANSPORT = 'tcp'
FORWARDER_SUBSCRIBER_PORT = 4400
FORWARDER_SUBSCRIBER_ENDPOINT = '%s://*:%d' % (FORWARDER_SUBSCRIBER_TRANSPORT,
                                               FORWARDER_SUBSCRIBER_PORT)
FORWARDER_PUBLISHER_PORT = 4500
FORWARDER_PUBLISHER_ENDPOINT = '%s://*:%d' % (FORWARDER_PUBLISHER_TRANSPORT,
                                              FORWARDER_PUBLISHER_PORT)
