# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/defo/Documentos/Universidad/Picnet/src/dsem/win/terminal/gui/ui_files/mainwin.ui'
#
# Created: Sun Oct 26 22:31:50 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1061, 785)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_6 = QtGui.QGroupBox(Form)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.line_envio = QtGui.QLineEdit(self.groupBox_6)
        self.line_envio.setObjectName("line_envio")
        self.gridLayout_8.addWidget(self.line_envio, 0, 0, 1, 4)
        self.pushLimpiar = QtGui.QPushButton(self.groupBox_6)
        self.pushLimpiar.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/draw-eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushLimpiar.setIcon(icon)
        self.pushLimpiar.setObjectName("pushLimpiar")
        self.gridLayout_8.addWidget(self.pushLimpiar, 1, 3, 1, 1)
        self.pushEnviar = QtGui.QPushButton(self.groupBox_6)
        self.pushEnviar.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/go-last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushEnviar.setIcon(icon1)
        self.pushEnviar.setObjectName("pushEnviar")
        self.gridLayout_8.addWidget(self.pushEnviar, 1, 2, 1, 1)
        self.combo_modo = QtGui.QComboBox(self.groupBox_6)
        self.combo_modo.setObjectName("combo_modo")
        self.combo_modo.addItem(QtCore.QString())
        self.combo_modo.addItem(QtCore.QString())
        self.gridLayout_8.addWidget(self.combo_modo, 1, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_6)
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_6)
        self.groupBox_4 = QtGui.QGroupBox(Form)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEnvio = QtGui.QPlainTextEdit(self.groupBox_4)
        self.textEnvio.setMinimumSize(QtCore.QSize(376, 120))
        self.textEnvio.setReadOnly(True)
        self.textEnvio.setObjectName("textEnvio")
        self.verticalLayout_3.addWidget(self.textEnvio)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.check_send_hexa = QtGui.QCheckBox(self.groupBox_4)
        self.check_send_hexa.setChecked(True)
        self.check_send_hexa.setObjectName("check_send_hexa")
        self.horizontalLayout_5.addWidget(self.check_send_hexa)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setMaximumSize(QtCore.QSize(24, 24))
        self.label_7.setPixmap(QtGui.QPixmap("res/view-sort-ascending.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setMinimumSize(QtCore.QSize(121, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit.setMaximumSize(QtCore.QSize(61, 16777215))
        self.lineEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(Form)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.textReceived = QtGui.QPlainTextEdit(self.groupBox_5)
        self.textReceived.setMinimumSize(QtCore.QSize(376, 200))
        self.textReceived.setReadOnly(True)
        self.textReceived.setObjectName("textReceived")
        self.gridLayout_7.addWidget(self.textReceived, 0, 0, 4, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.check_del_slashn = QtGui.QCheckBox(self.groupBox_5)
        self.check_del_slashn.setObjectName("check_del_slashn")
        self.horizontalLayout.addWidget(self.check_del_slashn)
        self.check_recv_hexa = QtGui.QCheckBox(self.groupBox_5)
        self.check_recv_hexa.setChecked(True)
        self.check_recv_hexa.setObjectName("check_recv_hexa")
        self.horizontalLayout.addWidget(self.check_recv_hexa)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_21 = QtGui.QLabel(self.groupBox_5)
        self.label_21.setMaximumSize(QtCore.QSize(24, 24))
        self.label_21.setPixmap(QtGui.QPixmap("res/view-sort-descending.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout.addWidget(self.label_21)
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setMinimumSize(QtCore.QSize(121, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(61, 16777215))
        self.lineEdit_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.gridLayout_7.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setMaximumSize(QtCore.QSize(208, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.check_envio_serial = QtGui.QCheckBox(self.groupBox)
        self.check_envio_serial.setEnabled(False)
        self.check_envio_serial.setObjectName("check_envio_serial")
        self.gridLayout_2.addWidget(self.check_envio_serial, 0, 0, 1, 3)
        self.pushConnect_serial = QtGui.QPushButton(self.groupBox)
        self.pushConnect_serial.setMinimumSize(QtCore.QSize(100, 0))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/network-connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("res/network-disconnect.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushConnect_serial.setIcon(icon2)
        self.pushConnect_serial.setCheckable(False)
        self.pushConnect_serial.setObjectName("pushConnect_serial")
        self.gridLayout_2.addWidget(self.pushConnect_serial, 1, 0, 1, 2)
        self.pushConf_serial = QtGui.QPushButton(self.groupBox)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushConf_serial.setIcon(icon3)
        self.pushConf_serial.setObjectName("pushConf_serial")
        self.gridLayout_2.addWidget(self.pushConf_serial, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.labelConexionSerial = QtGui.QLabel(self.groupBox)
        self.labelConexionSerial.setMinimumSize(QtCore.QSize(0, 0))
        self.labelConexionSerial.setObjectName("labelConexionSerial")
        self.gridLayout_2.addWidget(self.labelConexionSerial, 2, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setMaximumSize(QtCore.QSize(208, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_status_socket = QtGui.QLabel(self.groupBox_2)
        self.label_status_socket.setMinimumSize(QtCore.QSize(91, 0))
        self.label_status_socket.setObjectName("label_status_socket")
        self.horizontalLayout_3.addWidget(self.label_status_socket)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 2)
        self.check_envio_socket = QtGui.QCheckBox(self.groupBox_2)
        self.check_envio_socket.setEnabled(False)
        self.check_envio_socket.setObjectName("check_envio_socket")
        self.gridLayout.addWidget(self.check_envio_socket, 0, 0, 1, 2)
        self.pushConf_socket = QtGui.QPushButton(self.groupBox_2)
        self.pushConf_socket.setIcon(icon3)
        self.pushConf_socket.setObjectName("pushConf_socket")
        self.gridLayout.addWidget(self.pushConf_socket, 1, 1, 1, 1)
        self.pushConnect_socket = QtGui.QPushButton(self.groupBox_2)
        self.pushConnect_socket.setMinimumSize(QtCore.QSize(100, 0))
        self.pushConnect_socket.setIcon(icon2)
        self.pushConnect_socket.setCheckable(False)
        self.pushConnect_socket.setObjectName("pushConnect_socket")
        self.gridLayout.addWidget(self.pushConnect_socket, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_14 = QtGui.QGroupBox(Form)
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_14)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_8.addWidget(self.checkBox_3)
        self.pushHex2Bin = QtGui.QPushButton(self.groupBox_14)
        self.pushHex2Bin.setObjectName("pushHex2Bin")
        self.verticalLayout_8.addWidget(self.pushHex2Bin)
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_14)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_8.addWidget(self.pushButton_3)
        self.verticalLayout_4.addWidget(self.groupBox_14)
        self.push_about = QtGui.QPushButton(Form)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("res/games-hint.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_about.setIcon(icon4)
        self.push_about.setObjectName("push_about")
        self.verticalLayout_4.addWidget(self.push_about)
        self.pushButton_12 = QtGui.QPushButton(Form)
        self.pushButton_12.setMinimumSize(QtCore.QSize(0, 48))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("res/system-shutdown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon5)
        self.pushButton_12.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_4.addWidget(self.pushButton_12)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.groupBox_3 = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(295, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtGui.QScrollArea(self.groupBox_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -280, 252, 1006))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setMinimumSize(QtCore.QSize(0, 20))
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 2, 1, 1)
        self.spinOrigen = HexSpinBox(self.scrollAreaWidgetContents)
        self.spinOrigen.setMinimum(1)
        self.spinOrigen.setMaximum(254)
        self.spinOrigen.setObjectName("spinOrigen")
        self.gridLayout_3.addWidget(self.spinOrigen, 1, 0, 1, 1)
        self.spinDestino = HexSpinBox(self.scrollAreaWidgetContents)
        self.spinDestino.setMinimum(1)
        self.spinDestino.setMaximum(254)
        self.spinDestino.setProperty("value", QtCore.QVariant(3))
        self.spinDestino.setObjectName("spinDestino")
        self.gridLayout_3.addWidget(self.spinDestino, 1, 1, 1, 1)
        self.spinSecuencia = HexSpinBox(self.scrollAreaWidgetContents)
        self.spinSecuencia.setMinimum(0)
        self.spinSecuencia.setMaximum(255)
        self.spinSecuencia.setProperty("value", QtCore.QVariant(0))
        self.spinSecuencia.setObjectName("spinSecuencia")
        self.gridLayout_3.addWidget(self.spinSecuencia, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.groupBox_12 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pushSendReqEv = QtGui.QPushButton(self.groupBox_12)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("res/help-contents.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushSendReqEv.setIcon(icon6)
        self.pushSendReqEv.setObjectName("pushSendReqEv")
        self.gridLayout_11.addWidget(self.pushSendReqEv, 0, 0, 1, 1)
        self.pushSendReqMorEv = QtGui.QPushButton(self.groupBox_12)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("res/address-book-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushSendReqMorEv.setIcon(icon7)
        self.pushSendReqMorEv.setObjectName("pushSendReqMorEv")
        self.gridLayout_11.addWidget(self.pushSendReqMorEv, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_12)
        self.groupBox_7 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_10 = QtGui.QLabel(self.groupBox_7)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 1)
        self.spinPuerto = HexSpinBox(self.groupBox_7)
        self.spinPuerto.setMinimum(0)
        self.spinPuerto.setMaximum(254)
        self.spinPuerto.setObjectName("spinPuerto")
        self.gridLayout_4.addWidget(self.spinPuerto, 0, 1, 1, 2)
        self.label_11 = QtGui.QLabel(self.groupBox_7)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.spinBit = HexSpinBox(self.groupBox_7)
        self.spinBit.setMinimum(0)
        self.spinBit.setMaximum(7)
        self.spinBit.setObjectName("spinBit")
        self.gridLayout_4.addWidget(self.spinBit, 1, 1, 1, 2)
        self.label_12 = QtGui.QLabel(self.groupBox_7)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 2, 0, 1, 1)
        self.radioBitUno = QtGui.QRadioButton(self.groupBox_7)
        self.radioBitUno.setChecked(True)
        self.radioBitUno.setObjectName("radioBitUno")
        self.gridLayout_4.addWidget(self.radioBitUno, 2, 1, 1, 1)
        self.radioBitCero = QtGui.QRadioButton(self.groupBox_7)
        self.radioBitCero.setObjectName("radioBitCero")
        self.gridLayout_4.addWidget(self.radioBitCero, 2, 2, 1, 1)
        self.pushControl = QtGui.QPushButton(self.groupBox_7)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("res/run-build.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushControl.setIcon(icon8)
        self.pushControl.setObjectName("pushControl")
        self.gridLayout_4.addWidget(self.pushControl, 4, 0, 1, 3)
        self.checkIndirecto = QtGui.QCheckBox(self.groupBox_7)
        self.checkIndirecto.setObjectName("checkIndirecto")
        self.gridLayout_4.addWidget(self.checkIndirecto, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushPuestaEnHora = QtGui.QPushButton(self.groupBox_8)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("res/edit-clear-history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushPuestaEnHora.setIcon(icon9)
        self.pushPuestaEnHora.setObjectName("pushPuestaEnHora")
        self.verticalLayout_6.addWidget(self.pushPuestaEnHora)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.groupBox_9 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_14 = QtGui.QLabel(self.groupBox_9)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_9)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_9)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 2, 1, 1)
        self.spinDireccion = HexSpinBox(self.groupBox_9)
        self.spinDireccion.setMinimum(1)
        self.spinDireccion.setMaximum(254)
        self.spinDireccion.setProperty("value", QtCore.QVariant(3))
        self.spinDireccion.setObjectName("spinDireccion")
        self.gridLayout_5.addWidget(self.spinDireccion, 1, 1, 1, 1)
        self.spinCantidad = HexSpinBox(self.groupBox_9)
        self.spinCantidad.setMinimum(0)
        self.spinCantidad.setMaximum(255)
        self.spinCantidad.setProperty("value", QtCore.QVariant(0))
        self.spinCantidad.setObjectName("spinCantidad")
        self.gridLayout_5.addWidget(self.spinCantidad, 1, 2, 1, 1)
        self.spinPagina = HexSpinBox(self.groupBox_9)
        self.spinPagina.setMinimum(1)
        self.spinPagina.setMaximum(254)
        self.spinPagina.setObjectName("spinPagina")
        self.gridLayout_5.addWidget(self.spinPagina, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 3)
        self.label_17 = QtGui.QLabel(self.groupBox_9)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 1, 0, 1, 1)
        self.lineMemoryData = QtGui.QLineEdit(self.groupBox_9)
        self.lineMemoryData.setObjectName("lineMemoryData")
        self.gridLayout_6.addWidget(self.lineMemoryData, 1, 1, 1, 2)
        self.pushLeerEE = QtGui.QPushButton(self.groupBox_9)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("res/page-zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushLeerEE.setIcon(icon10)
        self.pushLeerEE.setObjectName("pushLeerEE")
        self.gridLayout_6.addWidget(self.pushLeerEE, 2, 0, 1, 2)
        self.pushEscribirEE = QtGui.QPushButton(self.groupBox_9)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("res/im-status-message-edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushEscribirEE.setIcon(icon11)
        self.pushEscribirEE.setObjectName("pushEscribirEE")
        self.gridLayout_6.addWidget(self.pushEscribirEE, 2, 2, 1, 1)
        self.pushLeerRam = QtGui.QPushButton(self.groupBox_9)
        self.pushLeerRam.setIcon(icon10)
        self.pushLeerRam.setObjectName("pushLeerRam")
        self.gridLayout_6.addWidget(self.pushLeerRam, 3, 0, 1, 3)
        self.verticalLayout.addWidget(self.groupBox_9)
        self.groupBox_11 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label = QtGui.QLabel(self.groupBox_11)
        self.label.setObjectName("label")
        self.gridLayout_10.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_9 = QtGui.QSpinBox(self.groupBox_11)
        self.spinBox_9.setObjectName("spinBox_9")
        self.gridLayout_10.addWidget(self.spinBox_9, 0, 1, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_11)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_10.addWidget(self.pushButton_8, 1, 0, 2, 1)
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_11)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_10.addWidget(self.pushButton_9, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_11)
        self.groupBox_10 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineAppString = QtGui.QLineEdit(self.groupBox_10)
        self.lineAppString.setObjectName("lineAppString")
        self.verticalLayout_7.addWidget(self.lineAppString)
        self.pushEnviarAppString = QtGui.QPushButton(self.groupBox_10)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("res/system-run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushEnviarAppString.setIcon(icon12)
        self.pushEnviarAppString.setObjectName("pushEnviarAppString")
        self.verticalLayout_7.addWidget(self.pushEnviarAppString)
        self.verticalLayout.addWidget(self.groupBox_10)
        self.groupBox_13 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_13)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_19 = QtGui.QLabel(self.groupBox_13)
        self.label_19.setObjectName("label_19")
        self.gridLayout_9.addWidget(self.label_19, 0, 0, 1, 1)
        self.lineDirRange = QtGui.QLineEdit(self.groupBox_13)
        self.lineDirRange.setObjectName("lineDirRange")
        self.gridLayout_9.addWidget(self.lineDirRange, 0, 1, 1, 2)
        self.label_20 = QtGui.QLabel(self.groupBox_13)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 1, 0, 1, 2)
        self.spinBox_10 = QtGui.QSpinBox(self.groupBox_13)
        self.spinBox_10.setMinimum(1)
        self.spinBox_10.setMaximum(999999)
        self.spinBox_10.setSingleStep(10)
        self.spinBox_10.setProperty("value", QtCore.QVariant(200))
        self.spinBox_10.setObjectName("spinBox_10")
        self.gridLayout_9.addWidget(self.spinBox_10, 1, 2, 1, 1)
        self.checkRequerirEstados = QtGui.QCheckBox(self.groupBox_13)
        self.checkRequerirEstados.setObjectName("checkRequerirEstados")
        self.gridLayout_9.addWidget(self.checkRequerirEstados, 2, 0, 1, 3)
        self.checkRequerirEventos = QtGui.QCheckBox(self.groupBox_13)
        self.checkRequerirEventos.setObjectName("checkRequerirEventos")
        self.gridLayout_9.addWidget(self.checkRequerirEventos, 3, 0, 1, 3)
        self.verticalLayout.addWidget(self.groupBox_13)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_2.addWidget(self.groupBox_3)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.pushLimpiar, QtCore.SIGNAL("pressed()"), self.textReceived.clear)
        QtCore.QObject.connect(self.pushLimpiar, QtCore.SIGNAL("pressed()"), self.textEnvio.clear)
        QtCore.QObject.connect(self.pushButton_12, QtCore.SIGNAL("pressed()"), Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Picnet Terminal", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Form", "Datos envío", None, QtGui.QApplication.UnicodeUTF8))
        self.pushLimpiar.setToolTip(QtGui.QApplication.translate("Form", "Envía la cadena mediante el Socket o el puerto RS232", None, QtGui.QApplication.UnicodeUTF8))
        self.pushLimpiar.setText(QtGui.QApplication.translate("Form", "Limpiar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushEnviar.setToolTip(QtGui.QApplication.translate("Form", "Envía la cadena mediante el Socket o el puerto RS232", None, QtGui.QApplication.UnicodeUTF8))
        self.pushEnviar.setText(QtGui.QApplication.translate("Form", "Enviar", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_modo.setToolTip(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Cambia el modo en el cual se interpreta la cadena <span style=\" font-weight:600;\">String Transporte</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_modo.setItemText(0, QtGui.QApplication.translate("Form", "Hexadecimal", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_modo.setItemText(1, QtGui.QApplication.translate("Form", "ASCII", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Formato de entrada:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Form", "Envio", None, QtGui.QApplication.UnicodeUTF8))
        self.check_send_hexa.setToolTip(QtGui.QApplication.translate("Form", "Recepción en hexadecimal", None, QtGui.QApplication.UnicodeUTF8))
        self.check_send_hexa.setText(QtGui.QApplication.translate("Form", "Hexa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Bytes enviados", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Form", "Recepción", None, QtGui.QApplication.UnicodeUTF8))
        self.check_del_slashn.setToolTip(QtGui.QApplication.translate("Form", "Elimina los caracteres \\n finalizadores. Util cuando se reciben cadenas de texto.", None, QtGui.QApplication.UnicodeUTF8))
        self.check_del_slashn.setText(QtGui.QApplication.translate("Form", "Suprimir \\n", None, QtGui.QApplication.UnicodeUTF8))
        self.check_recv_hexa.setToolTip(QtGui.QApplication.translate("Form", "Recepción en hexa\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.check_recv_hexa.setText(QtGui.QApplication.translate("Form", "Hexa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "Bytes recibidos", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Comunicación RS232", None, QtGui.QApplication.UnicodeUTF8))
        self.check_envio_serial.setText(QtGui.QApplication.translate("Form", "Enviar por RS232", None, QtGui.QApplication.UnicodeUTF8))
        self.pushConnect_serial.setText(QtGui.QApplication.translate("Form", "Conectar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushConf_serial.setText(QtGui.QApplication.translate("Form", "Conf.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Estado:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelConexionSerial.setText(QtGui.QApplication.translate("Form", "Sin conexión", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Comunicación TCP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Estado:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_status_socket.setText(QtGui.QApplication.translate("Form", "Sin conexión", None, QtGui.QApplication.UnicodeUTF8))
        self.check_envio_socket.setText(QtGui.QApplication.translate("Form", "Enviar por socket", None, QtGui.QApplication.UnicodeUTF8))
        self.pushConf_socket.setToolTip(QtGui.QApplication.translate("Form", "Configuración del socket.\n"
"Cada vez que cambie la configuración", None, QtGui.QApplication.UnicodeUTF8))
        self.pushConf_socket.setText(QtGui.QApplication.translate("Form", "Conf.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushConnect_socket.setText(QtGui.QApplication.translate("Form", "Conectar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_14.setTitle(QtGui.QApplication.translate("Form", "Extras", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setToolTip(QtGui.QApplication.translate("Form", "Cuando se presiona el botón enviar en un comando, se realiza automáticamente el envío, si se encuentra conectado.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("Form", "Auto envío de comandos", None, QtGui.QApplication.UnicodeUTF8))
        self.pushHex2Bin.setText(QtGui.QApplication.translate("Form", "Hexa a binario", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Form", "Idetificar paquete", None, QtGui.QApplication.UnicodeUTF8))
        self.push_about.setText(QtGui.QApplication.translate("Form", "Acerca del terminal", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("Form", "Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Comandos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setToolTip(QtGui.QApplication.translate("Form", "Dirección origen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Origen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setToolTip(QtGui.QApplication.translate("Form", "Dirección Destino", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Destino", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setToolTip(QtGui.QApplication.translate("Form", "Número de secuencia. 0..255", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Sec.", None, QtGui.QApplication.UnicodeUTF8))
        self.spinOrigen.setToolTip(QtGui.QApplication.translate("Form", "Dirección origen", None, QtGui.QApplication.UnicodeUTF8))
        self.spinDestino.setToolTip(QtGui.QApplication.translate("Form", "Dirección Destino", None, QtGui.QApplication.UnicodeUTF8))
        self.spinSecuencia.setToolTip(QtGui.QApplication.translate("Form", "Número de secuencia. 0..255", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("Form", "Estados y eventos", None, QtGui.QApplication.UnicodeUTF8))
        self.pushSendReqEv.setToolTip(QtGui.QApplication.translate("Form", "Trae los estados del micro y posiblemente eventos", None, QtGui.QApplication.UnicodeUTF8))
        self.pushSendReqEv.setText(QtGui.QApplication.translate("Form", "Estados", None, QtGui.QApplication.UnicodeUTF8))
        self.pushSendReqMorEv.setToolTip(QtGui.QApplication.translate("Form", "Pide eventos", None, QtGui.QApplication.UnicodeUTF8))
        self.pushSendReqMorEv.setText(QtGui.QApplication.translate("Form", "MorEv", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Form", "Control de bits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setToolTip(QtGui.QApplication.translate("Form", "Dirección origen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Puerto", None, QtGui.QApplication.UnicodeUTF8))
        self.spinPuerto.setToolTip(QtGui.QApplication.translate("Form", "Dirección origen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setToolTip(QtGui.QApplication.translate("Form", "Dirección origen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Bit", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBit.setToolTip(QtGui.QApplication.translate("Form", "Dirección origen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setToolTip(QtGui.QApplication.translate("Form", "Dirección origen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Función", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBitUno.setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.radioBitCero.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushControl.setText(QtGui.QApplication.translate("Form", "Enviar", None, QtGui.QApplication.UnicodeUTF8))
        self.checkIndirecto.setText(QtGui.QApplication.translate("Form", "Indirecto", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Form", "PeH y sincronizmo", None, QtGui.QApplication.UnicodeUTF8))
        self.pushPuestaEnHora.setText(QtGui.QApplication.translate("Form", "Enviar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("Form", "Acceso a RAM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setToolTip(QtGui.QApplication.translate("Form", "Dirección origen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Página", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setToolTip(QtGui.QApplication.translate("Form", "Dirección Destino", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Dir.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setToolTip(QtGui.QApplication.translate("Form", "Número de secuencia. 0..255", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Cant.", None, QtGui.QApplication.UnicodeUTF8))
        self.spinDireccion.setToolTip(QtGui.QApplication.translate("Form", "Dirección Destino", None, QtGui.QApplication.UnicodeUTF8))
        self.spinCantidad.setToolTip(QtGui.QApplication.translate("Form", "Número de secuencia. 0..255", None, QtGui.QApplication.UnicodeUTF8))
        self.spinPagina.setToolTip(QtGui.QApplication.translate("Form", "Dirección origen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Valor:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushLeerEE.setText(QtGui.QApplication.translate("Form", "Leer E²", None, QtGui.QApplication.UnicodeUTF8))
        self.pushEscribirEE.setText(QtGui.QApplication.translate("Form", "Escribir E²", None, QtGui.QApplication.UnicodeUTF8))
        self.pushLeerRam.setText(QtGui.QApplication.translate("Form", "Leer RAM", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("Form", "Eventos Dummy", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Cantidad", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("Form", "Eventos", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("Form", "Boradcast", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("Form", "String Aplicación", None, QtGui.QApplication.UnicodeUTF8))
        self.pushEnviarAppString.setText(QtGui.QApplication.translate("Form", "Enviar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_13.setTitle(QtGui.QApplication.translate("Form", "Scan Periódico", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Form", "Rango", None, QtGui.QApplication.UnicodeUTF8))
        self.lineDirRange.setText(QtGui.QApplication.translate("Form", "3-4,5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Form", "Intervalo", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_10.setSuffix(QtGui.QApplication.translate("Form", " mS", None, QtGui.QApplication.UnicodeUTF8))
        self.checkRequerirEstados.setText(QtGui.QApplication.translate("Form", "Requerir Estados", None, QtGui.QApplication.UnicodeUTF8))
        self.checkRequerirEventos.setText(QtGui.QApplication.translate("Form", "Requerir Eventos", None, QtGui.QApplication.UnicodeUTF8))

from hexspinbox import HexSpinBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

