# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/defo/Documentos/Universidad/Picnet/src/ucnet/win/winlauncher/gui/uis/configwindow.ui'
#
# Created: Wed Aug  6 23:12:49 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(298,513)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../res/oxy/actions/configure.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox_profname = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_profname.setObjectName("comboBox_profname")
        self.gridLayout_3.addWidget(self.comboBox_profname,0,0,1,4)
        self.pushButton_newprof = QtGui.QPushButton(self.groupBox_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/oxy/actions/document-new.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.pushButton_newprof.setIcon(icon)
        self.pushButton_newprof.setIconSize(QtCore.QSize(22,22))
        self.pushButton_newprof.setObjectName("pushButton_newprof")
        self.gridLayout_3.addWidget(self.pushButton_newprof,1,0,1,1)
        self.pushButton_saveprof = QtGui.QPushButton(self.groupBox_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/oxy/actions/view-calendar-tasks.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.pushButton_saveprof.setIcon(icon)
        self.pushButton_saveprof.setIconSize(QtCore.QSize(22,22))
        self.pushButton_saveprof.setObjectName("pushButton_saveprof")
        self.gridLayout_3.addWidget(self.pushButton_saveprof,1,1,1,1)
        self.pushButton_loadprof = QtGui.QPushButton(self.groupBox_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/oxy/actions/document-import.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.pushButton_loadprof.setIcon(icon)
        self.pushButton_loadprof.setIconSize(QtCore.QSize(22,22))
        self.pushButton_loadprof.setObjectName("pushButton_loadprof")
        self.gridLayout_3.addWidget(self.pushButton_loadprof,1,2,1,1)
        self.pushButton_delprof = QtGui.QPushButton(self.groupBox_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/oxy/actions/draw-eraser.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.pushButton_delprof.setIcon(icon)
        self.pushButton_delprof.setIconSize(QtCore.QSize(22,22))
        self.pushButton_delprof.setObjectName("pushButton_delprof")
        self.gridLayout_3.addWidget(self.pushButton_delprof,1,3,1,1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_port = QtGui.QLabel(self.groupBox_2)
        self.label_port.setObjectName("label_port")
        self.gridLayout_2.addWidget(self.label_port,2,0,1,1)
        self.label_addr = QtGui.QLabel(self.groupBox_2)
        self.label_addr.setObjectName("label_addr")
        self.gridLayout_2.addWidget(self.label_addr,0,0,1,1)
        self.lineEdit_addr = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_addr.setObjectName("lineEdit_addr")
        self.gridLayout_2.addWidget(self.lineEdit_addr,0,1,1,1)
        self.lineEdit_port = QtGui.QSpinBox(self.groupBox_2)
        self.lineEdit_port.setMinimum(1024)
        self.lineEdit_port.setMaximum(65000)
        self.lineEdit_port.setProperty("value",QtCore.QVariant(8000))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.gridLayout_2.addWidget(self.lineEdit_port,2,1,1,1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label,3,0,1,1)
        self.label_link = QtGui.QLabel(self.groupBox_2)
        self.label_link.setObjectName("label_link")
        self.gridLayout_2.addWidget(self.label_link,3,1,1,1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_DB_type = QtGui.QLabel(self.groupBox)
        self.label_DB_type.setObjectName("label_DB_type")
        self.gridLayout.addWidget(self.label_DB_type,0,0,1,1)
        self.comboBox_DB_type = QtGui.QComboBox(self.groupBox)
        self.comboBox_DB_type.setObjectName("comboBox_DB_type")
        self.gridLayout.addWidget(self.comboBox_DB_type,0,1,1,2)
        self.label_DB_name = QtGui.QLabel(self.groupBox)
        self.label_DB_name.setObjectName("label_DB_name")
        self.gridLayout.addWidget(self.label_DB_name,1,0,1,1)
        self.lineEdit_DB_name = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_DB_name.setObjectName("lineEdit_DB_name")
        self.gridLayout.addWidget(self.lineEdit_DB_name,1,2,1,1)
        self.label_DB_user = QtGui.QLabel(self.groupBox)
        self.label_DB_user.setObjectName("label_DB_user")
        self.gridLayout.addWidget(self.label_DB_user,2,0,1,2)
        self.lineEdit_DB_user = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_DB_user.setObjectName("lineEdit_DB_user")
        self.gridLayout.addWidget(self.lineEdit_DB_user,2,2,1,1)
        self.label_DB_pass = QtGui.QLabel(self.groupBox)
        self.label_DB_pass.setObjectName("label_DB_pass")
        self.gridLayout.addWidget(self.label_DB_pass,3,0,1,1)
        self.lineEdit_DB_pass = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_DB_pass.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_DB_pass.setObjectName("lineEdit_DB_pass")
        self.gridLayout.addWidget(self.lineEdit_DB_pass,3,2,1,1)
        self.label_DB_server = QtGui.QLabel(self.groupBox)
        self.label_DB_server.setObjectName("label_DB_server")
        self.gridLayout.addWidget(self.label_DB_server,4,0,1,1)
        self.lineEdit_DB_server = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_DB_server.setObjectName("lineEdit_DB_server")
        self.gridLayout.addWidget(self.lineEdit_DB_server,4,2,1,1)
        self.label_DB_port = QtGui.QLabel(self.groupBox)
        self.label_DB_port.setObjectName("label_DB_port")
        self.gridLayout.addWidget(self.label_DB_port,5,0,1,1)
        self.lineEdit_DB_port = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_DB_port.setObjectName("lineEdit_DB_port")
        self.gridLayout.addWidget(self.lineEdit_DB_port,5,2,1,1)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox,QtCore.SIGNAL("accepted()"),Dialog.accept)
        QtCore.QObject.connect(self.buttonBox,QtCore.SIGNAL("rejected()"),Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Configuración µC Net", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Perfiles", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_newprof.setToolTip(QtGui.QApplication.translate("Dialog", "Nuevo perfil", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_saveprof.setToolTip(QtGui.QApplication.translate("Dialog", "Guardar perfil", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_loadprof.setToolTip(QtGui.QApplication.translate("Dialog", "Cargar perfil", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_delprof.setToolTip(QtGui.QApplication.translate("Dialog", "Borrar perfil", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Servidor HMI µC Net", None, QtGui.QApplication.UnicodeUTF8))
        self.label_port.setToolTip(QtGui.QApplication.translate("Dialog", "Puerto en el cual escuchara conexiones web el HMI del motor SCADA.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_port.setText(QtGui.QApplication.translate("Dialog", "Puerto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_addr.setToolTip(QtGui.QApplication.translate("Dialog", "Dirección sobre la cual escuchará conexiones. Por defecto, loopback, 127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_addr.setText(QtGui.QApplication.translate("Dialog", "Dirección", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_addr.setToolTip(QtGui.QApplication.translate("Dialog", "Dirección sobre la cual escuchará conexiones. Por defecto, loopback, 127.0.0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_addr.setText(QtGui.QApplication.translate("Dialog", "localhost", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Acceder a:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_link.setText(QtGui.QApplication.translate("Dialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Base de datos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_DB_type.setText(QtGui.QApplication.translate("Dialog", "Tipo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_DB_type.addItem(QtGui.QApplication.translate("Dialog", "SQLite (interna)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_DB_type.addItem(QtGui.QApplication.translate("Dialog", "MySQL", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_DB_type.addItem(QtGui.QApplication.translate("Dialog", "PostgreSQL", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_DB_type.addItem(QtGui.QApplication.translate("Dialog", "Oracle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_DB_name.setToolTip(QtGui.QApplication.translate("Dialog", "Nombre de la base de datos, en SQLite es solo el nombre del archivo.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_DB_name.setText(QtGui.QApplication.translate("Dialog", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_DB_name.setToolTip(QtGui.QApplication.translate("Dialog", "Nombre de la base de datos, en SQLite es solo el nombre del archivo.", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_DB_name.setText(QtGui.QApplication.translate("Dialog", "db/db.sqlite", None, QtGui.QApplication.UnicodeUTF8))
        self.label_DB_user.setToolTip(QtGui.QApplication.translate("Dialog", "Nombre de usuario para conectarse a la base de datos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_DB_user.setText(QtGui.QApplication.translate("Dialog", "Nombre de usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_DB_user.setToolTip(QtGui.QApplication.translate("Dialog", "Nombre de usuario para conectarse a la base de datos", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_DB_user.setText(QtGui.QApplication.translate("Dialog", "foo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_DB_pass.setToolTip(QtGui.QApplication.translate("Dialog", "Contraseña para acceder a la base de datos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_DB_pass.setText(QtGui.QApplication.translate("Dialog", "Contraseña", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_DB_pass.setToolTip(QtGui.QApplication.translate("Dialog", "Contraseña para acceder a la base de datos", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_DB_pass.setText(QtGui.QApplication.translate("Dialog", "foo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_DB_server.setToolTip(QtGui.QApplication.translate("Dialog", "Servidor de la base de datos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_DB_server.setText(QtGui.QApplication.translate("Dialog", "Servidor", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_DB_server.setToolTip(QtGui.QApplication.translate("Dialog", "Servidor de la base de datos", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_DB_server.setText(QtGui.QApplication.translate("Dialog", "localhost", None, QtGui.QApplication.UnicodeUTF8))
        self.label_DB_port.setToolTip(QtGui.QApplication.translate("Dialog", "Puerto de la base de datos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_DB_port.setText(QtGui.QApplication.translate("Dialog", "Puerto", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_DB_port.setToolTip(QtGui.QApplication.translate("Dialog", "Puerto de la base de datos", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_DB_port.setText(QtGui.QApplication.translate("Dialog", "3306", None, QtGui.QApplication.UnicodeUTF8))

