# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui_files/confdlg.ui'
#
# Created: Sat Feb  7 21:51:00 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(377, 389)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabDB = QtGui.QWidget()
        self.tabDB.setObjectName("tabDB")
        self.verticalLayout = QtGui.QVBoxLayout(self.tabDB)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.tabDB)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.comboDBType = QtGui.QComboBox(self.tabDB)
        self.comboDBType.setObjectName("comboDBType")
        self.comboDBType.addItem(QtCore.QString())
        self.comboDBType.addItem(QtCore.QString())
        self.comboDBType.addItem(QtCore.QString())
        self.comboDBType.addItem(QtCore.QString())
        self.comboDBType.addItem(QtCore.QString())
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboDBType)
        self.label_2 = QtGui.QLabel(self.tabDB)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineDBName = QtGui.QLineEdit(self.tabDB)
        self.lineDBName.setObjectName("lineDBName")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineDBName)
        self.pushBrowse = QPushBtnEnabler(self.tabDB)
        self.pushBrowse.setEnabled(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushBrowse.setIcon(icon)
        self.pushBrowse.setObjectName("pushBrowse")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.pushBrowse)
        self.labelUser = QtGui.QLabel(self.tabDB)
        self.labelUser.setObjectName("labelUser")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelUser)
        self.lineUser = QtGui.QLineEdit(self.tabDB)
        self.lineUser.setObjectName("lineUser")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineUser)
        self.labelPass = QtGui.QLabel(self.tabDB)
        self.labelPass.setObjectName("labelPass")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelPass)
        self.linePass = QtGui.QLineEdit(self.tabDB)
        self.linePass.setObjectName("linePass")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.linePass)
        self.labelServer = QtGui.QLabel(self.tabDB)
        self.labelServer.setObjectName("labelServer")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.labelServer)
        self.lineServer = QtGui.QLineEdit(self.tabDB)
        self.lineServer.setObjectName("lineServer")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineServer)
        self.labelPort = QtGui.QLabel(self.tabDB)
        self.labelPort.setObjectName("labelPort")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.labelPort)
        self.spinPort = QtGui.QSpinBox(self.tabDB)
        self.spinPort.setMinimum(1)
        self.spinPort.setMaximum(65536)
        self.spinPort.setObjectName("spinPort")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.spinPort)
        self.labelOptions = QtGui.QLabel(self.tabDB)
        self.labelOptions.setObjectName("labelOptions")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.labelOptions)
        self.lineOptions = QtGui.QLineEdit(self.tabDB)
        self.lineOptions.setObjectName("lineOptions")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineOptions)
        self.verticalLayout.addLayout(self.formLayout)
        self.label_3 = QtGui.QLabel(self.tabDB)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.tabWidget.addTab(self.tabDB, "")
        self.tabCom = QtGui.QWidget()
        self.tabCom.setObjectName("tabCom")
        self.formLayout_2 = QtGui.QFormLayout(self.tabCom)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_9 = QtGui.QLabel(self.tabCom)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.spinPicnetTcpPort = QtGui.QSpinBox(self.tabCom)
        self.spinPicnetTcpPort.setMinimum(1)
        self.spinPicnetTcpPort.setMaximum(65364)
        self.spinPicnetTcpPort.setProperty("value", QtCore.QVariant(9761))
        self.spinPicnetTcpPort.setObjectName("spinPicnetTcpPort")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinPicnetTcpPort)
        self.tabWidget.addTab(self.tabCom, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Config SCADA", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Tipo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboDBType.setItemText(0, QtGui.QApplication.translate("Dialog", "MySQL", None, QtGui.QApplication.UnicodeUTF8))
        self.comboDBType.setItemText(1, QtGui.QApplication.translate("Dialog", "SQLite (interna)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboDBType.setItemText(2, QtGui.QApplication.translate("Dialog", "MS SQL Server", None, QtGui.QApplication.UnicodeUTF8))
        self.comboDBType.setItemText(3, QtGui.QApplication.translate("Dialog", "Postgres", None, QtGui.QApplication.UnicodeUTF8))
        self.comboDBType.setItemText(4, QtGui.QApplication.translate("Dialog", "Oracle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setToolTip(QtGui.QApplication.translate("Dialog", "Nombre de la base de datos o esquema (Schema).\n"
"En SQLite es el nombre del archivo.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Nombre de base", None, QtGui.QApplication.UnicodeUTF8))
        self.lineDBName.setText(QtGui.QApplication.translate("Dialog", "dsem", None, QtGui.QApplication.UnicodeUTF8))
        self.pushBrowse.setText(QtGui.QApplication.translate("Dialog", "Base SQLite...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelUser.setText(QtGui.QApplication.translate("Dialog", "Nombre de usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.lineUser.setText(QtGui.QApplication.translate("Dialog", "dsem", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPass.setText(QtGui.QApplication.translate("Dialog", "Contraseña", None, QtGui.QApplication.UnicodeUTF8))
        self.linePass.setText(QtGui.QApplication.translate("Dialog", "passmenot", None, QtGui.QApplication.UnicodeUTF8))
        self.labelServer.setText(QtGui.QApplication.translate("Dialog", "Servidor", None, QtGui.QApplication.UnicodeUTF8))
        self.lineServer.setText(QtGui.QApplication.translate("Dialog", "localhost", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPort.setText(QtGui.QApplication.translate("Dialog", "Puerto", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOptions.setText(QtGui.QApplication.translate("Dialog", "Opciones", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Los cambios en la cofiguracion de la base de datos\n"
"requieren reiniciar la aplicaion para tomar efecto.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDB), QtGui.QApplication.translate("Dialog", "Base de datos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Puerto de comunicaciones con el campo:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCom), QtGui.QApplication.translate("Dialog", "Comunicaciones", None, QtGui.QApplication.UnicodeUTF8))

from customwidgets import QPushBtnEnabler
import data_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

