FORWARDER_SUB_TRANSPORT = FORWARDER_PUB_TRANSPORT = 'tcp'
FORWARDER_SUB_PORT = 4400
FORWARDER_SUB_ENDPOINT = '%s://*:%d' % (FORWARDER_SUB_TRANSPORT,
                                        FORWARDER_SUB_PORT)

FORWARDER_PUB_PORT = 4500
FORWARDER_PUB_ENDPOINT = '%s://*:%d' % (FORWARDER_PUB_TRANSPORT,
                                        FORWARDER_PUB_PORT)
FORWARDER_PUB_CONN = '%s://localhost:%d' % (FORWARDER_PUB_TRANSPORT,
                                            FORWARDER_PUB_PORT)
