# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui_files/mainwin.ui'
#
# Created: Fri Nov 21 15:21:51 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(919, 566)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabMapa = QtGui.QWidget()
        self.tabMapa.setObjectName("tabMapa")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabMapa)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gvMapa = ZoomingScrollingGraphicsView(self.tabMapa)
        self.gvMapa.setObjectName("gvMapa")
        self.verticalLayout_4.addWidget(self.gvMapa)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.tabMapa)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.tabMapa)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.tabMapa)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.tabMapa)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabMapa, icon, "")
        self.tabEventos = QtGui.QWidget()
        self.tabEventos.setObjectName("tabEventos")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabEventos)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtGui.QTableWidget(self.tabEventos)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/view-file-columns.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabEventos, icon1, "")
        self.tabEsquina = QtGui.QWidget()
        self.tabEsquina.setObjectName("tabEsquina")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabEsquina)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gvEsquina = QtGui.QGraphicsView(self.tabEsquina)
        self.gvEsquina.setObjectName("gvEsquina")
        self.verticalLayout_3.addWidget(self.gvEsquina)
        self.tabWidget.addTab(self.tabEsquina, "")
        self.tabConfiguracion = QtGui.QWidget()
        self.tabConfiguracion.setObjectName("tabConfiguracion")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabConfiguracion)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtGui.QLabel(self.tabConfiguracion)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.lineSMFPath = QtGui.QLineEdit(self.tabConfiguracion)
        self.lineSMFPath.setObjectName("lineSMFPath")
        self.verticalLayout_5.addWidget(self.lineSMFPath)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushBuscar = QtGui.QPushButton(self.tabConfiguracion)
        self.pushBuscar.setObjectName("pushBuscar")
        self.horizontalLayout_3.addWidget(self.pushBuscar)
        self.pushCargarSMF = QtGui.QPushButton(self.tabConfiguracion)
        self.pushCargarSMF.setObjectName("pushCargarSMF")
        self.horizontalLayout_3.addWidget(self.pushCargarSMF)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem2 = QtGui.QSpacerItem(20, 370, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabConfiguracion, icon2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 919, 27))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuConfiguraci_n = QtGui.QMenu(self.menubar)
        self.menuConfiguraci_n.setObjectName("menuConfiguraci_n")
        self.menuAyuda = QtGui.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        self.menuSCADA = QtGui.QMenu(self.menubar)
        self.menuSCADA.setObjectName("menuSCADA")
        self.menuDebug = QtGui.QMenu(self.menubar)
        self.menuDebug.setObjectName("menuDebug")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSalir.setIcon(icon3)
        self.actionSalir.setObjectName("actionSalir")
        self.actionSobre_PySemControl = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/res/view-statistics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSobre_PySemControl.setIcon(icon4)
        self.actionSobre_PySemControl.setObjectName("actionSobre_PySemControl")
        self.actionIniciar = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/res/media-playback-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIniciar.setIcon(icon5)
        self.actionIniciar.setObjectName("actionIniciar")
        self.actionDetener = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/res/media-playback-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDetener.setIcon(icon6)
        self.actionDetener.setObjectName("actionDetener")
        self.actionReiniciar = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/res/object-rotate-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReiniciar.setIcon(icon7)
        self.actionReiniciar.setObjectName("actionReiniciar")
        self.actionRegistro_de_eventos = QtGui.QAction(MainWindow)
        self.actionRegistro_de_eventos.setIcon(icon1)
        self.actionRegistro_de_eventos.setObjectName("actionRegistro_de_eventos")
        self.actionMostrar_ventana_de_registro = QtGui.QAction(MainWindow)
        self.actionMostrar_ventana_de_registro.setObjectName("actionMostrar_ventana_de_registro")
        self.menuArchivo.addAction(self.actionSalir)
        self.menuAyuda.addAction(self.actionSobre_PySemControl)
        self.menuSCADA.addAction(self.actionIniciar)
        self.menuSCADA.addAction(self.actionDetener)
        self.menuSCADA.addAction(self.actionReiniciar)
        self.menuSCADA.addAction(self.actionRegistro_de_eventos)
        self.menuDebug.addAction(self.actionMostrar_ventana_de_registro)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuConfiguraci_n.menuAction())
        self.menubar.addAction(self.menuSCADA.menuAction())
        self.menubar.addAction(self.menuDebug.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionSalir, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Inferfase Hombre Máquina", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", " X: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "0000,000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", " Y: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "0000,000", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMapa), QtGui.QApplication.translate("MainWindow", "Visualización Mapa", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Semáforo", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Descripción envento", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Hora de reporte", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Hora de atención", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEventos), QtGui.QApplication.translate("MainWindow", "Listado de Eventos", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEsquina), QtGui.QApplication.translate("MainWindow", "Visualización esquina", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Cargar archivo de temoporización <span style=\" font-weight:600;\">SMF</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushBuscar.setText(QtGui.QApplication.translate("MainWindow", "Buscar...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushCargarSMF.setText(QtGui.QApplication.translate("MainWindow", "Cargar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConfiguracion), QtGui.QApplication.translate("MainWindow", "Configuración", None, QtGui.QApplication.UnicodeUTF8))
        self.menuArchivo.setTitle(QtGui.QApplication.translate("MainWindow", "Archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConfiguraci_n.setTitle(QtGui.QApplication.translate("MainWindow", "Configuración", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAyuda.setTitle(QtGui.QApplication.translate("MainWindow", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSCADA.setTitle(QtGui.QApplication.translate("MainWindow", "SCADA", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDebug.setTitle(QtGui.QApplication.translate("MainWindow", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setText(QtGui.QApplication.translate("MainWindow", "Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSobre_PySemControl.setText(QtGui.QApplication.translate("MainWindow", "Sobre PySemControl", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIniciar.setText(QtGui.QApplication.translate("MainWindow", "Iniciar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDetener.setText(QtGui.QApplication.translate("MainWindow", "Detener", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReiniciar.setText(QtGui.QApplication.translate("MainWindow", "Reiniciar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegistro_de_eventos.setText(QtGui.QApplication.translate("MainWindow", "Registro de eventos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMostrar_ventana_de_registro.setText(QtGui.QApplication.translate("MainWindow", "Mostrar ventana de registro", None, QtGui.QApplication.UnicodeUTF8))

from zoominggv import ZoomingScrollingGraphicsView
import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

